<nav class="globalmenu">
                    <nav class="navbar navbar-expand-lg navbar-dark">
                      <a class="navbar-brand" href="index.php"><img src="closure-logo-white.png"></a>
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                          <label class="burgermenu-line"></label>
                          <label class="burgermenu-line" class="line-margintop"></label>
                          <label class="burgermenu-line" class="line-margintop"></label>
                          <!-- labels til at lave tre hvide linjer som brugermenu ikon-->
                      </button> <!-- burgermenuen -->

                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                          <li class="nav-item active">
                            <a class="nav-link" id="nav-link-uxui" href="design-thinking/designthinking.php">Design Thinking </a>
                          </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  Kodning
                                </a>
                                <div class="dropdown-menu" id="kodning-dropdown" aria-labelledby="navbarDropdown">
                                  <a class="dropdown-item" href="kodning/html/attributter/attributter.php">HTML</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="kodning/serverer/server.php">Serverer</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="kodning/css/boxmodellen/boxmodellen.php">CSS</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="kodning/versionsstyring/versionsstyring.php">Versionsstyring</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="kodning/php/php.php">PHP</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="kodning/bootstrap/">Bootstrap</a>
                                    <div class="dropdown-divider"></div>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  Kommunikation
                                </a>
                                <div class="dropdown-menu" id="kommunikation-dropdown" aria-labelledby="navbarDropdown">
                                  <a class="dropdown-item" href="kommunikation/hvad-er-kommunikation/hvad-er-kommunikation.php">Hvad er kommunikation?</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="kommunikation/paradigmer/humanistisk/humanistisk.php">Paradigmer</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="kommunikation/empiri/kvalitativ/kvalitativ.php">Empiri</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="kommunikation/presentationsteknik/opskrift/opskrifttilgodtale.php">Præsentationsteknik</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="kommunikation/informationsarkitektur/Latch/lacth.php">Informationsarkitektur</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="kommunikation/licensering/licens.php">Ophavsret og Licensering</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="kommunikation/bmc/bmc.php">BMC</a>
                                    <div class="dropdown-divider"></div>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  Usability
                                </a>
                                <div class="dropdown-menu" id="usability-dropdown" aria-labelledby="navbarDropdown">
                                  <a class="dropdown-item" href="usability/hvaderusability/hvad-er-usability.php">Hvad er Usability?</a>
                                    <div class="dropdown-divider"></div>  
                                  <a class="dropdown-item" href="usability/gangstertest/gangstertest.php">Gangstertest</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="usability/sp%25C3%25B8rgeskema/sporgeskema.php">Spørgeskema</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="usability/ekspertvudering/ekspertvudering.php">Ekspertvudering</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="usability/kortsortering/kortsortering.php">Kortsortering</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="usability/brugertest/brugertest.php">Brugertest</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="usability/tilg%25C3%25A6ngelighedstest/tilgangelighed.php">Tilgængelighedstest</a>
                                    <div class="dropdown-divider"></div>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  Design
                                </a>
                                <div class="dropdown-menu" id="design-dropdown" aria-labelledby="navbarDropdown">
                                  <a class="dropdown-item" href="design/photoshop/smokeythebear/smokeythebear.php">Photoshop</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="design/illustrator/artboards/artboards.php">Illustrator</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="design/farver/farver.php">Farver</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="design/typografi/typografi.php">Typografi</a>
                                    <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="design/gestaltlovene/gestaltlove.php">Gestaltlovene</a>
                                  <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="design/wireframing/lo-fi/lofi.php">Wireframing</a>
                                    <div class="dropdown-divider"></div>
                                </div>
                            </li>

                            <li class="nav-item active">
                                <a class="nav-link" id="nav-link-ui2" href="video/videoproduktion.php">Videoproduktion </a>
                            </li>
                            
                            <li class="nav-item active">
                                <a class="nav-link" id="nav-link-ui3" href="foto/fotografering.php">Fotografering </a>
                            </li>
                            
                            <li class="nav-item active">
                                <a class="nav-link" id="nav-link-projekter" href="projekter/projekter.php"> Projekter</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Om siden
                                </a>
                                <div class="dropdown-menu" id="omsiden-dropdown" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="om-siden/refleksion/refleksion.php">Refleksion</a>
                                        <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Kilder</a>
                                        <div class="dropdown-divider"></div>
                                </div>
                            </li>
                        </ul>
                      </div> <!-- menulisten -->
                    </nav> <!-- bootstrap navbar component -->                    
                </nav> <!-- Global menu til mobil og tablet -->
                
                <!-- DESKTOP  GLOBAL MENU -->
                    <nav class="globalmenu-desktop">
                        <nav class="navbar navbar-expand-lg navbar-custom">
                          <a class="navbar-brand" href="index.php"><img src="closure-logo-white.png"></a>
                          <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item active">
                                    <a class="nav-link" id="nav-link-uxui-desktop" href="design-thinking/designthinking.php">Design Thinking </a>
                                </li>
                              <div class="dropdown-menu-mega">
                                  <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      Kodning
                                    </a>
                                        <div class="dropdown-menu" id="background-kodning" aria-labelledby="navbarDropdown">
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>HTML</h3></li>
                                            <li><a class="dropdown-item" href="kodning/html/attributter/attributter.php">Attributter</a></li>
                                            <li><a class="dropdown-item" href="kodning/html/kodeskikke/kodeskikke.php">Kodeskikke</a></li>
                                            <li><a class="dropdown-item" href="kodning/html/semantisketags/semantisketags.php">Semantiske tags</a></li>
                                            <li><a class="dropdown-item" href="kodning/html/seo/seo.php">SEO</a></li>
                                            <li><a class="dropdown-item" href="kodning/html/metadata/metadata.php">Metadata</a></li>
                                            <li><a class="dropdown-item" href="kodning/html/adressering/adressering.php">Adressering</a></li>
                                            <li><a class="dropdown-item" href="kodning/html/videoogbilleder/videoogbilleder.php">Video og Billeder</a></li>
                                            <li><a class="dropdown-item" href="kodning/html/formularer/formularer.php">Formularer, felttyper og formatering</a></li>
                                          </ul> 
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Serverer</h3></li>
                                            <li><a class="dropdown-item" href="kodning/serverer/server.php">Serverer</a></li>
                                          </ul>
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>CSS</h3></li>
                                            <li><a class="dropdown-item" href="kodning/css/boxmodellen/boxmodellen.php">Boxmodellen</a></li>
                                            <li><a class="dropdown-item" href="kodning/css/selectors/selectors.php">Selectors</a></li>
                                            <li><a class="dropdown-item" href="kodning/css/properties/properties.php">Properties</a></li>
                                            <li><a class="dropdown-item" href="kodning/css/positionering/position.php">Positionering</a></li>
                                            <li><a class="dropdown-item" href="kodning/css/grid/cssgrid.php">CSS Grid</a></li>
                                          </ul>
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Versionsstyring</h3></li>
                                            <li><a class="dropdown-item" href="kodning/versionsstyring/versionsstyring.php">Versionsstyring</a></li>
                                          </ul>
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>PHP</h3></li>
                                            <li><a class="dropdown-item" href="kodning/php/php.php">PHP</a></li>
                                          </ul>
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Bootstrap</h3></li>
                                            <li><a class="dropdown-item" href="kodning/bootstrap/bootstrap.php">Bootstrap</a></li>
                                          </ul>
                                        </div>
                                    </li> <!-- mega dropdown -->
                                 </div> <!-- container til styling for mega dropdown -->
                                 <div class="dropdown-menu-mega">
                                  <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      Kommunikation
                                    </a>
                                        <div class="dropdown-menu" id="background-kommunikation" aria-labelledby="navbarDropdown">
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Hvad er Kommunikation?</h3></li>
                                            <li><a class="dropdown-item" href="kommunikation/hvad-er-kommunikation/hvad-er-kommunikation.php">Hvad er kommunikation?</a></li>
                                          </ul> 
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Paradigmer</h3></li>
                                            <li><a class="dropdown-item" href="kommunikation/paradigmer/humanistisk/humanistisk.php">Humanistiske</a></li>
                                            <li><a class="dropdown-item" href="kommunikation/paradigmer/samfundsvidenskablig/samfundsvidenskabelig.php">Samfundsvidenskablige</a></li>
                                          </ul>
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Empiri</h3></li>
                                            <li><a class="dropdown-item" href="kommunikation/empiri/kvalitativ/kvalitativ.php">Kvalitativ</a></li>
                                            <li><a class="dropdown-item" href="kommunikation/empiri/kvantitativ/kvantitativ.php">Kvantitativ</a></li>
                                          </ul>
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Præsentationsteknik</h3></li>
                                            <li><a class="dropdown-item" href="kommunikation/presentationsteknik/opskrift/opskrifttilgodtale.php">Den Gode Præsentation</a></li>
                                            <li><a class="dropdown-item" href="kommunikation/presentationsteknik/powerpoint/deathbypowerpoint.php">Death by Powerpoint</a></li>
                                          </ul>
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Informationsarkitektur</h3></li>
                                            <li><a class="dropdown-item" href="kommunikation/informationsarkitektur/Latch/lacth.php">LATCH</a></li>
                                            <li><a class="dropdown-item" href="kommunikation/informationsarkitektur/webstruktur/webstruktur.php">Webstruktur</a></li>
                                            <li><a class="dropdown-item" href="kommunikation/informationsarkitektur/navigeringsdesign/navigering.php">Navigeringsdesign</a></li>
                                          </ul>
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Ophavsret og Licensering</h3></li>
                                            <li><a class="dropdown-item" href="kommunikation/licensering/licens.php">Ophavsret og Licensering</a></li>
                                          </ul>
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Business Model Canvas</h3></li>
                                            <li><a class="dropdown-item" href="kommunikation/bmc/bmc.php">BMC</a></li>
                                          </ul>
                                        </div>
                                    </li> <!-- mega dropdown -->
                                 </div> <!-- container til styling for mega dropdown -->
                                 <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      Usability
                                    </a>
                                    <div class="dropdown-menu" id="background-usability" aria-labelledby="navbarDropdown">
                                          <a class="dropdown-item" href="usability/hvaderusability/hvad-er-usability.php">Hvad er Usability?</a>
                                          <a class="dropdown-item" href="usability/gangstertest/gangstertest.php">Gangstertest</a>
                                          <a class="dropdown-item" href="usability/sp%25C3%25B8rgeskema/sporgeskema.php">Spørgeskema</a>
                                          <a class="dropdown-item" href="usability/ekspertvudering/ekspertvudering.php">Ekspertvudering</a>
                                          <a class="dropdown-item" href="usability/kortsortering/kortsortering.php">Kortsortering</a>
                                          <a class="dropdown-item" href="usability/brugertest/brugertest.php">Brugertest</a>
                                          <a class="dropdown-item" href="usability/tilg%25C3%25A6ngelighedstest/tilgangelighed.php">Tilgængelighedstest</a>
                                    </div>
                                  </li> <!-- standard dropdown class="dropdown-standard" -->
                                <div class="dropdown-menu-mega">
                                  <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      Design
                                    </a>
                                        <div class="dropdown-menu" id="background-design" aria-labelledby="navbarDropdown">
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Illustrator</h3></li>
                                            <li><a class="dropdown-item" href="design/illustrator/artboards/artboards.php">Artboards</a></li>
                                            <li><a class="dropdown-item" href="design/illustrator/blendtool/blendtool.php">Blend tool</a></li>
                                            <li><a class="dropdown-item" href="design/illustrator/captainamerica/captainamerica.php">Captain America</a></li>
                                            <li><a class="dropdown-item" href="design/illustrator/directselectiontool/directselection.php">Direct Selection Tool</a></li>
                                            <li><a class="dropdown-item" href="design/illustrator/shapebuildertool/shapebuildertool.php">Shape Builder Tool</a></li>
                                          </ul> 
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Photoshop</h3></li>
                                            <li><a class="dropdown-item" href="design/photoshop/smokeythebear/smokeythebear.php">Smokey the Bear</a></li>
                                            <li><a class="dropdown-item" href="design/photoshop/smooth/smooth.php">Smooth</a></li>
                                            <li><a class="dropdown-item" href="design/photoshop/contentawarefill/contentawarefill.php">Content Aware Fill</a></li>
                                            <li><a class="dropdown-item" href="design/photoshop/spothealingtool/spothealingtool.php">Spot Healing Tool</a></li>
                                            <li><a class="dropdown-item" href="design/photoshop/smartobject/smartobject.php">Smart Object</a></li>
                                            <li><a class="dropdown-item" href="design/photoshop/outofframe/outofframe.php">Out of Frame</a></li>
                                          </ul>
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Farver</h3></li>
                                            <li><a class="dropdown-item" href="design/farver/farver.php">Farver</a></li>
                                          </ul>
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Typografi</h3></li>
                                            <li><a class="dropdown-item" href="design/typografi/typografi.php">Typografi</a></li>
                                          </ul>
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Gestaltlovene</h3></li>
                                            <li><a class="dropdown-item" href="design/gestaltlovene/gestaltlove.php">Gestaltlovene</a></li>
                                          </ul>
                                          <ul class="mega-dropdown-desktop">
                                            <li class="mega-menu-list-title"><h3>Wireframing</h3></li>
                                            <li><a class="dropdown-item" href="design/wireframing/lo-fi/lofi.php">Lo-Fi</a></li>
                                            <li><a class="dropdown-item" href="design/wireframing/lo-fi/hifi.php">Hi-Fi</a></li>
                                          </ul>
                                        </div>
                                    </li> <!-- mega dropdown -->
                                 </div> <!-- container til styling for mega dropdown -->
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      Video og Foto
                                    </a>
                                    <div class="dropdown-menu" id="background-videoogfoto" aria-labelledby="navbarDropdown">
                                      <a class="dropdown-item" id="video-link-dektop" href="video/videoproduktion.php">Videoproduktion</a>
                                      <a class="dropdown-item" id="fotografering-link-desktop" href="foto/fotografering.php">Fotografering</a>
                                    </div>
                                </li> <!-- standard dropdown class="dropdown-standard" -->
                                <li class="nav-item active">
                                    <a class="nav-link" href="projekter/projekter.php">Projekter </a>
                                </li>
                              <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  Om siden
                                </a>
                                <div class="dropdown-menu" id="menulisteflyt-omsiden" aria-labelledby="navbarDropdown">
                                  <a class="dropdown-item" href="om-siden/refleksion/refleksion.php">Refleksion</a>
                                  <a class="dropdown-item" href="om-siden/kilder/kilder.php">Kilder</a>
                                </div>
                              </li> <!-- standard dropdown class="dropdown-standard" -->
                            </ul>
                          </div>
                        </nav> <!-- bootstrap menu -->
                    </nav> <!-- global menu desktop -->                 
                <!-- DESKTOP  GLOBAL MENU -->