<nav class="undermenu-mobil">
                <p class="main-button">
                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                         Vis flere emner
                    </button>
                </p>
                <div class="collapse" id="collapseExample">
                      <div class="card card-body">
                        <a href="lacth.php"><button type="button" class="btn btn-primary">LATCH</button></a>
                        <a href="webstruktur.php"><button type="button" class="btn btn-primary">Webstruktur</button></a>
                        <a href="navigering.php"><button type="button" class="btn btn-primary">Navigeringsdesign</button></a>
                    </div>
                </div>
            </nav> <!-- undermenu mobil -->