<nav class="undermenu-mobil">
                <p class="main-button">
                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                         Vis flere emner
                    </button>
                </p>
                <div class="collapse" id="collapseExample">
                      <div class="card card-body">
                        <a href="opskrifttilgodtale.php"><button type="button" class="btn btn-primary">Den Gode Præsentation</button></a>
                        <a href="deathbypowerpoint.php"><button type="button" class="btn btn-primary">Death by Powerpoint</button></a>
                    </div>
                </div>
            </nav> <!-- undermenu mobil -->