        <nav class="undermenu-mobil">
            <p class="main-button">
                <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                     Vis flere emner
                </button>
            </p>
            <div class="collapse" id="collapseExample">
                  <div class="card card-body">
                    <a href="fundamental-html.php"><button type="button" class="btn btn-primary">Grundlæggende HTML</button></a>
                    <a href="seo.php"><button type="button" class="btn btn-primary">SEO, Semantiske tags og Metadata</button></a>
                    <a href="adressering.php"><button type="button" class="btn btn-primary">Adressering</button></a>
                    <a href="videoogbilleder.php"><button type="button" class="btn btn-primary">Video og Billeder</button></a>
                    <a href="formularer.php"><button type="button" class="btn btn-primary">Formularer</button></a>
                </div>
            </div>
        </nav> <!-- undermenu mobil -->