<nav class="undermenu-mobil">
                <p class="main-button">
                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                         Vis flere emner
                    </button>
                </p>
                <div class="collapse" id="collapseExample">
                      <div class="card card-body">
                        <a href="boxmodellen.php"><button type="button" class="btn btn-primary">Boxmodellen</button></a>
                        <a href="background-property.php"><button type="button" class="btn btn-primary">CSS Background</button></a>
                        <a href="cssgrid.php"><button type="button" class="btn btn-primary">CSS Grid</button></a>
                        <a href="displayogposition.php"><button type="button" class="btn btn-primary">Display og Position</button></a>
                        <a href="list-style.php"><button type="button" class="btn btn-primary">List-Style</button></a>
                        <a href="selectors.php"><button type="button" class="btn btn-primary">Selectors</button></a>
                        <a href="animationogtransistions.php"><button type="button" class="btn btn-primary">Animation og Transistions</button></a>
                        <a href="media-queries.php"><button type="button" class="btn btn-primary">&#64;Media</button></a>
                    </div>
                </div>
            </nav> <!-- undermenu mobil -->