<nav class="undermenu-mobil">
                <p class="main-button">
                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                         Vis flere emner
                    </button>
                </p>
                <div class="collapse" id="collapseExample">
                      <div class="card card-body">
                        <a href="smokeythebear.php"><button type="button" class="btn btn-primary">Smokey the Bear</button></a>
                        <a href="smooth.php"><button type="button" class="btn btn-primary">Warped</button></a>
                        <a href="contentawarefill.php"><button type="button" class="btn btn-primary">Content aware fill</button></a>
                        <a href="spothealingtool.php"><button type="button" class="btn btn-primary">Spot healing tool</button></a>
                        <a href="smartobject.php"><button type="button" class="btn btn-primary">Smart object</button></a>
                        <a href="outofframe.php"><button type="button" class="btn btn-primary">Out of Frame</button></a>
                        <a href="saturation.php"><button type="button" class="btn btn-primary">Saturation</button></a>
                    </div>
                </div>
            </nav> <!-- undermenu mobil -->